# App Info
# ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Wobbly                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Just-add-water iOS animation wobbly is a bunch of cool, fun, and easy to use iOS animations for you to use in your projects. Animation types taken from Animate CSS (Animate CSS for iOS ðŸ‘»).

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Sagaya Abdulhafeez                                
your_link                                 : https://github.com/sagaya                     
your_city                                 : Lagos                                
email_address                             : shaggy.hafeez@gmail.com
facebook_username                         :                                           
instagram_username                        : sagaya_hafeez
twitter_username                          : sagaya_hafeez
github_username                           : sagaya
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Easy to use
    description                           : Designed to work with all views and can be activated with just one line of code. e.g `view.shake` VoilÃ¡!
    fontawesome_icon_name                 : magic

  - title                                 : Custom Duration
    description                           : It can be easily customized by setting custom duration for the animation (Coming soon...).
    fontawesome_icon_name                 : play-circle

  - title                                 : Storyboard Support
    description                           : You can just activate the animation inside storyboard (Coming Soon...)
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Easy Installation
    description                           : You can easily install through cocoapods ot just drag the "wobbly" folder inside your project BOOM! âœ¨
    fontawesome_icon_name                 : download



# Theme Settings
topbar_color                              : "#ffff"
topbar_transparency                       : 1.0
topbar_title_color                        : "#000"

# cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffff"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#F8F8F8"

link_color                                : "#1d63ea"

app_title_color                           : "#000"
app_price_color                           : "#000"
app_description_color                     : "#000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
